version: '3.1'

services:
  db:
    image: postgres:11-alpine
    volumes:
      # To persist the data beyond the life of the container we configure a volume. 
      # This config will bind postgres_data to the "/var/lib/postgresql/data/" 
      # directory in the container.
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command:
      sh /code/entrypoint.sh
      # sh -c "python manage.py runserver 0.0.0.0:8000"  
    environment:
      - env_file
    depends_on:
      - db

volumes:
  postgres_data: